"""
step_impl.py — Auto-generated by step_generator.py
Do NOT edit manually; re-run step_generator.py to regenerate.

Requirements:
    pip install getgauge selenium webdriver-manager
"""

from getgauge.python import step, before_scenario, after_scenario, Messages
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager

driver = None
WAIT_TIMEOUT = 10


# ---------------------------------------------------------------------------
# Hooks
# ---------------------------------------------------------------------------

@before_scenario
def before_scenario_hook():
    global driver
    options = Options()
    options.add_argument("--start-maximized")
    # options.add_argument("--headless")   # uncomment for CI/headless runs
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    service = Service(ChromeDriverManager().install())
    driver = webdriver.Chrome(service=service, options=options)
    driver.implicitly_wait(WAIT_TIMEOUT)


@after_scenario
def after_scenario_hook():
    global driver
    if driver:
        driver.quit()
        driver = None


# ---------------------------------------------------------------------------
# Generated Steps
# ---------------------------------------------------------------------------


@step("Navigate to url <url>")
def navigate_to_url(url):
    driver.get(url)
    Messages.write_message(f"Navigated to: {url}")


@step("Verify heading with xpath <xpath> contains <expected_text>")
def verify_heading_with_xpath(xpath, expected_text):
    element = WebDriverWait(driver, WAIT_TIMEOUT).until(
        EC.presence_of_element_located((By.XPATH, xpath))
    )
    actual_text = element.text
    assert expected_text in actual_text, (
        f"Expected heading to contain '{expected_text}', but got '{actual_text}'"
    )
    Messages.write_message(f"Heading verified: '{actual_text}'")        


@step("Verify test outcome is <outcome>")
def verify_test_outcome(outcome):
    Messages.write_message(f"Expected outcome: {outcome}")


@step("Click on link with text <link_text>")
def click_on_link_with_text(link_text):
    element = WebDriverWait(driver, WAIT_TIMEOUT).until(
        EC.element_to_be_clickable((By.LINK_TEXT, link_text))
    )
    element.click()
    Messages.write_message(f"Clicked link: '{link_text}'")        


@step("Enter <value> in input with id <field_id>")
def enter_value_in_input_with_id(value, field_id):
    element = WebDriverWait(driver, WAIT_TIMEOUT).until(
        EC.presence_of_element_located((By.ID, field_id))
    )
    element.clear()
    element.send_keys(value)
    Messages.write_message(f"Entered '{value}' in input id='{field_id}'")        


@step("Click on button with name <name>")
def click_on_button_with_name(name):
    element = WebDriverWait(driver, WAIT_TIMEOUT).until(
        EC.element_to_be_clickable((By.NAME, name))
    )
    element.click()
    Messages.write_message(f"Clicked button name='{name}'")        


@step("Clear field with id <field_id>")
def clear_field_with_id(field_id):
    element = WebDriverWait(driver, WAIT_TIMEOUT).until(
        EC.presence_of_element_located((By.ID, field_id))
    )
    element.clear()
    Messages.write_message(f"Cleared input id='{field_id}'")        


@step("Verify element with name <name> is visible")
def verify_element_with_name_is_visible(name):
    element = WebDriverWait(driver, WAIT_TIMEOUT).until(
        EC.visibility_of_element_located((By.NAME, name))
    )
    assert element.is_displayed(), f"Element name='{name}' is not visible"
    Messages.write_message(f"Element '{name}' is visible")        


@step("Enter <value> in input with name <field_name>")
def enter_value_in_input_with_name(value, field_name):
    element = WebDriverWait(driver, WAIT_TIMEOUT).until(
        EC.presence_of_element_located((By.NAME, field_name))
    )
    element.clear()
    element.send_keys(value)
    Messages.write_message(f"Entered '{value}' in input name='{field_name}'")        

