"""
ai_steps.py  (AUTO-GENERATED by step_impl_generator.py)
=========================================================
Report ID  : 20260305_114132_edb9739e
Target URL : https://www.calculators.net/
Generated  : 20260305_114210

DO NOT EDIT — regenerated on every pipeline run.
To add steps, edit step_impl_generator.py instead.
"""
from __future__ import annotations
import os, sys, time, re
from pathlib import Path
from dotenv import load_dotenv
from getgauge.python import (
    step, before_suite, after_suite,
    before_scenario, after_scenario,
    Messages, Screenshots
)

load_dotenv(Path(__file__).parent.parent.parent / ".env")
BASE_URL = os.getenv("BASE_URL", "https://www.calculators.net/")
_driver  = None


# ── Driver ──────────────────────────────────────────────────────────

def _get_driver():
    global _driver
    if _driver is None:
        sys.path.insert(0, str(Path(__file__).parent.parent.parent))
        from execution_layer.playwright_driver import PlaywrightDriver
        _driver = PlaywrightDriver()
    return _driver

def _page():
    return _get_driver().page

def _find(page, sel, timeout=5000):
    """Multi-strategy element finder."""
    for strat in [
        "#" + sel,
        "[name='" + sel + "']",
        "text=" + sel,
        "[aria-label*='" + sel + "' i]",
        "[placeholder*='" + sel + "' i]",
        "role=button[name='" + sel + "']",
        "role=link[name='" + sel + "']",
        "role=textbox[name='" + sel + "']",
        sel,
    ]:
        try:
            loc = page.locator(strat).first
            loc.wait_for(state="attached", timeout=timeout)
            return loc
        except Exception:
            continue
    raise RuntimeError("Element not found: " + str(sel))

def _safe(fn, msg):
    try:
        fn()
    except Exception as exc:
        Messages.write_message("WARNING: " + msg + " | " + str(exc))

def _kv(assertion):
    """Keyword-based soft verify — never hard-fails."""
    Screenshots.capture_screenshot()
    try:
        body = _page().locator("body").inner_text().lower()
    except Exception:
        body = ""
    words = [w for w in assertion.lower().split() if len(w) > 3]
    hits  = sum(1 for w in words if w in body)
    pct   = hits / max(len(words), 1)
    status = "PASS" if pct >= 0.35 else "WARN"
    Messages.write_message(status + " (" + str(round(pct*100)) + "%): " + assertion[:80])

def _click_btn(label):
    """Try multiple strategies to click a button by label."""
    page = _page()
    for loc_str in [
        "role=button[name='" + label + "']",
        "button:has-text('" + label + "')",
        "input[value='" + label + "']",
        "text=" + label,
        "[aria-label*='" + label + "' i]",
    ]:
        try:
            loc = page.locator(loc_str).first
            loc.wait_for(state="visible", timeout=3000)
            loc.click()
            Messages.write_message("Clicked button: " + label)
            return
        except Exception:
            continue
    Messages.write_message("WARNING: Button not found: " + label)

def _fill(text, field):
    """Try multiple strategies to fill a field."""
    page = _page()
    for strat in [
        "#" + field,
        "[name='" + field + "']",
        "[placeholder*='" + field + "' i]",
        "[aria-label*='" + field + "' i]",
        "role=textbox[name='" + field + "']",
        "input[type='text']",
        "input[type='search']",
        field,
    ]:
        try:
            el = page.locator(strat).first
            el.wait_for(state="visible", timeout=3000)
            el.clear()
            el.fill(text)
            Messages.write_message("Filled '" + field + "' with '" + text + "'")
            return
        except Exception:
            continue
    Messages.write_message("WARNING: Field not found: " + field)


# ── Lifecycle ────────────────────────────────────────────────────────

@before_suite
def before_suite_hook():
    _get_driver()
    Messages.write_message("Suite start | BASE_URL=" + BASE_URL)

@after_suite
def after_suite_hook():
    global _driver
    if _driver:
        try: _driver.close()
        except Exception: pass
        _driver = None

@before_scenario
def before_scenario_hook():
    try:
        Messages.write_message("Scenario start: " + _page().url)
    except Exception:
        pass

@after_scenario
def after_scenario_hook():
    Screenshots.capture_screenshot()


# ── Navigation ──────────────────────────────────────────────────────

@step("Open browser and navigate to base URL")
def open_browser():
    _page().goto(BASE_URL, wait_until="load")
    Messages.write_message("Opened: " + BASE_URL)

@step("Navigate to <url>")
def navigate_to(url):
    full = url if url.startswith("http") else BASE_URL.rstrip("/") + url
    _page().goto(full, wait_until="load")
    Messages.write_message("Navigated: " + full)

@step("Refresh the page")
def refresh_page():
    _page().reload(wait_until="load")

@step("Go back to previous page")
def go_back():
    _page().go_back(wait_until="load")

@step("Go forward to next page")
def go_forward():
    _page().go_forward(wait_until="load")


# ── Click ───────────────────────────────────────────────────────────

@step("Click on <element>")
def click_element(element):
    _safe(lambda: _find(_page(), element).click(),
          "click: " + element)

@step("Click button <label>")
def click_button(label):
    _click_btn(label)

@step("Click link <label>")
def click_link(label):
    _safe(
        lambda: _page().get_by_role("link", name=label).first.click(),
        "click link: " + label
    )

@step("Click on forgot password link")
def click_forgot_password():
    page = _page()
    for loc in [
        "text=Forgot Password", "text=Forgot password",
        "a[href*='forgot']", "a[href*='reset']",
        "text=Reset Password", "text=reset password",
    ]:
        try:
            page.locator(loc).first.click()
            Messages.write_message("Clicked forgot password")
            return
        except Exception:
            continue
    Messages.write_message("WARNING: forgot password link not found")

@step("Click on a navigation link")
def click_nav_link():
    page = _page()
    _safe(
        lambda: page.locator("nav a, header a, .nav a, .navbar a, .menu a").first.click(),
        "click nav link"
    )

@step("Double click on <element>")
def double_click(element):
    _safe(lambda: _find(_page(), element).dblclick(),
          "dblclick: " + element)

@step("Right click on <element>")
def right_click(element):
    _safe(lambda: _find(_page(), element).click(button="right"),
          "rclick: " + element)

@step("Hover over <element>")
def hover_element(element):
    _safe(lambda: _find(_page(), element).hover(),
          "hover: " + element)


# ── Input ───────────────────────────────────────────────────────────

@step("Enter <text> in <field>")
def enter_text(text, field):
    _fill(text, field)

@step("Type <text> in <field>")
def type_text(text, field):
    _fill(text, field)

@step("Clear field <field>")
def clear_field(field):
    _safe(lambda: _find(_page(), field).clear(),
          "clear: " + field)

@step("Select <option> from <dropdown>")
def select_option(option, dropdown):
    _safe(lambda: _find(_page(), dropdown).select_option(label=option),
          "select " + option)

@step("Check checkbox <label>")
def check_checkbox(label):
    _safe(lambda: _find(_page(), label).check(),
          "check: " + label)

@step("Uncheck checkbox <label>")
def uncheck_checkbox(label):
    _safe(lambda: _find(_page(), label).uncheck(),
          "uncheck: " + label)

@step("Upload file <filepath> to <field>")
def upload_file(filepath, field):
    _safe(lambda: _find(_page(), field).set_input_files(filepath),
          "upload: " + field)

@step("Press key <key>")
def press_key(key):
    _page().keyboard.press(key)
    Messages.write_message("Pressed: " + key)

@step("Enter a sql injection string in the login form")
def enter_sql_injection():
    page = _page()
    sql  = "' OR '1'='1"
    for loc in [
        "#username", "#email", "[name='username']",
        "[name='email']", "[placeholder*='username' i]",
        "input[type='text']",
    ]:
        try:
            el = page.locator(loc).first
            el.wait_for(state="visible", timeout=3000)
            el.fill(sql)
            Messages.write_message("Entered SQL injection")
            return
        except Exception:
            continue


# ── Submit ───────────────────────────────────────────────────────────

@step("Submit the form")
def submit_form():
    page = _page()
    def _do():
        for loc in [
            "button[type='submit']", "input[type='submit']",
            "button:has-text('Submit')", "button:has-text('Login')",
            "button:has-text('Sign in')", "button:has-text('Search')",
        ]:
            try:
                el = page.locator(loc).first
                el.wait_for(state="visible", timeout=2000)
                el.click()
                Messages.write_message("Submitted via: " + loc)
                return
            except Exception:
                continue
        page.keyboard.press("Enter")
        Messages.write_message("Submitted via Enter")
    _safe(_do, "submit form")
    try:
        page.wait_for_load_state("load", timeout=8000)
    except Exception:
        pass


# ── Scroll ───────────────────────────────────────────────────────────

@step("Scroll down")
def scroll_down():
    _page().evaluate("window.scrollBy(0, window.innerHeight)")

@step("Scroll down by <pixels> pixels")
def scroll_down_pixels(pixels):
    _page().evaluate("window.scrollBy(0, " + str(pixels) + ")")

@step("Scroll up")
def scroll_up():
    _page().evaluate("window.scrollBy(0, -window.innerHeight)")

@step("Scroll to <element>")
def scroll_to_element(element):
    _safe(lambda: _find(_page(), element).scroll_into_view_if_needed(),
          "scroll to: " + element)

@step("Focus on <element>")
def focus_element(element):
    _safe(lambda: _find(_page(), element).focus(),
          "focus: " + element)

@step("Drag <source> and drop on <target>")
def drag_drop(source, target):
    _safe(
        lambda: _find(_page(), source).drag_to(_find(_page(), target)),
        "drag " + source + " to " + target
    )


# ── Verify ───────────────────────────────────────────────────────────

@step("Verify: <assertion>")
def generic_verify(assertion):
    _kv(assertion)

@step("Verify page title contains <text>")
def verify_title(text):
    title = _page().title()
    assert text.lower() in title.lower(), \
        "Title should contain '" + text + "' got: " + title
    Messages.write_message("Title OK: " + title)

@step("Verify text <text> is visible")
def verify_text_visible(text):
    try:
        _page().locator("text=" + text).first.wait_for(
            state="visible", timeout=8000)
        Messages.write_message("Text visible: " + text)
    except Exception:
        raise AssertionError("Text not visible: " + text)

@step("Verify text <text> is not visible")
def verify_text_not_visible(text):
    try:
        _page().locator("text=" + text).first.wait_for(
            state="hidden", timeout=5000)
    except Exception:
        raise AssertionError("Text still visible: " + text)

@step("Verify element <sel> is visible")
def verify_element_visible(sel):
    try:
        _find(_page(), sel).wait_for(state="visible", timeout=8000)
        Messages.write_message("Element visible: " + sel)
    except Exception:
        raise AssertionError("Element not visible: " + sel)

@step("Verify element <sel> is hidden")
def verify_element_hidden(sel):
    try:
        _find(_page(), sel).wait_for(state="hidden", timeout=5000)
    except Exception:
        raise AssertionError("Element not hidden: " + sel)

@step("Verify current URL contains <path>")
def verify_url_contains(path):
    current = _page().url
    assert path in current, \
        "URL should contain '" + path + "' got: " + current
    Messages.write_message("URL OK: " + current)

@step("Verify input <field> has value <value>")
def verify_input_value(field, value):
    actual = _find(_page(), field).input_value()
    assert actual == value, \
        "Field '" + field + "' expected '" + value + "' got: " + actual


# ── Wait ────────────────────────────────────────────────────────────

@step("Wait for network idle")
def wait_network_idle():
    try:
        _page().wait_for_load_state("networkidle", timeout=10000)
    except Exception:
        pass
    Messages.write_message("Network idle")

@step("Wait for element <sel>")
def wait_for_element(sel):
    _safe(
        lambda: _find(_page(), sel).wait_for(state="visible", timeout=15000),
        "wait for: " + sel
    )

@step("Wait <seconds> seconds")
def wait_seconds(seconds):
    time.sleep(float(seconds))


# ── Screenshot ──────────────────────────────────────────────────────

@step("Take a screenshot")
def take_screenshot():
    Screenshots.capture_screenshot()


# ── Auth ────────────────────────────────────────────────────────────

@step("Log in with username <username> and password <password>")
def login(username, password):
    page = _page()
    for u_loc in [
        "#username", "#email", "[name='username']",
        "[name='email']", "[placeholder*='username' i]",
        "[placeholder*='email' i]",
    ]:
        try:
            el = page.locator(u_loc).first
            el.wait_for(state="visible", timeout=3000)
            el.fill(username)
            break
        except Exception:
            continue
    for p_loc in [
        "#password", "[name='password']",
        "[type='password']", "[placeholder*='password' i]",
    ]:
        try:
            el = page.locator(p_loc).first
            el.wait_for(state="visible", timeout=3000)
            el.fill(password)
            break
        except Exception:
            continue
    submit_form()
    Messages.write_message("Logged in as: " + username)

@step("Log out")
def logout():
    page = _page()
    for loc in [
        "text=Logout", "text=Log out", "text=Sign out",
        "[aria-label*='logout' i]", "#logout",
    ]:
        try:
            page.locator(loc).first.click()
            page.wait_for_load_state("load")
            Messages.write_message("Logged out")
            return
        except Exception:
            continue
    Messages.write_message("WARNING: logout element not found")


# ── Dialogs ─────────────────────────────────────────────────────────

@step("Accept dialog")
def accept_dialog():
    _page().on("dialog", lambda d: d.accept())

@step("Dismiss dialog")
def dismiss_dialog():
    _page().on("dialog", lambda d: d.dismiss())

@step("Close modal")
def close_modal():
    page = _page()
    for loc in [
        "button[aria-label='Close']", "button[aria-label='close']",
        ".modal-close", "[data-dismiss='modal']",
        "text=Close", "text=Cancel",
    ]:
        try:
            page.locator(loc).first.click()
            return
        except Exception:
            continue
    page.keyboard.press("Escape")


# ── Tabs ────────────────────────────────────────────────────────────

@step("Switch to tab <index>")
def switch_tab(index):
    pages = _get_driver().context.pages
    idx   = int(index) - 1
    if 0 <= idx < len(pages):
        pages[idx].bring_to_front()
        _get_driver().page = pages[idx]
        Messages.write_message("Switched to tab: " + str(index))


# ── Generic fallback ────────────────────────────────────────────────

@step("Perform action <description>")
def generic_action(description):
    Messages.write_message("Action: " + description)
    Screenshots.capture_screenshot()
