"""
gauge_runner.py
Orchestrates the full execution pipeline:
  1. StepImplGenerator -> writes execution_layer/step_impl/ai_steps.py
  2. SpecGenerator     -> writes execution_layer/specs/<report_id>.spec
  3. Writes env/default/default.properties
  4. Runs gauge run <spec_path>
  5. Parses output and returns results dict
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

from dotenv import load_dotenv

BASE_DIR      = Path(__file__).parent.parent
EXECUTION_DIR = Path(__file__).parent

sys.path.insert(0, str(BASE_DIR))

load_dotenv(BASE_DIR / ".env")


class GaugeRunner:

    def __init__(self, report_id: str):
        self.report_id       = report_id
        self.specs_dir       = EXECUTION_DIR / "specs"
        self.reports_dir     = BASE_DIR / "reports"
        self.screenshots_dir = self.reports_dir / "screenshots"
        self.json_store      = BASE_DIR / "intelligence_layer" / "json_store"

        for d in (self.specs_dir, self.reports_dir, self.screenshots_dir):
            d.mkdir(parents=True, exist_ok=True)

    def run(self, url: str, test_cases: list[dict[str, Any]]) -> dict:
        json_path = self.json_store / f"{self.report_id}.json"

        print("[GaugeRunner] Step 1: Generating step implementations...")
        self._generate_step_impl(json_path)

        print("[GaugeRunner] Step 2: Generating spec file...")
        spec_path = self._generate_spec(json_path)

        print("[GaugeRunner] Step 3: Writing gauge env...")
        self._write_env(url)

        print(f"[GaugeRunner] Step 4: Running gauge on {spec_path.name}...")
        raw_output, exit_code = self._execute_gauge(spec_path)

        results = self._parse_results(raw_output, exit_code)
        results_path = self.reports_dir / f"{self.report_id}_results.json"
        results_path.write_text(json.dumps(results, indent=2))

        print(f"[GaugeRunner] Done. Passed={results['passed']} Failed={results['failed']}")
        return results

    def _generate_step_impl(self, json_path: Path):
        from step_impl_generator import StepImplGenerator
        output_path = EXECUTION_DIR / "step_impl" / "ai_steps.py"
        output_path.parent.mkdir(exist_ok=True)
        try:
            StepImplGenerator(json_path=json_path, output_path=output_path).generate()
            print(f"[GaugeRunner] ai_steps.py generated -> {output_path}")
        except Exception as exc:
            print(f"[GaugeRunner] WARNING: StepImplGenerator failed: {exc}")

    def _generate_spec(self, json_path: Path) -> Path:
        from spec_generator import SpecGenerator
        try:
            spec_path = SpecGenerator(
                json_path=json_path, output_dir=self.specs_dir
            ).generate()
            print(f"[GaugeRunner] Spec generated -> {spec_path}")
            return spec_path
        except Exception as exc:
            print(f"[GaugeRunner] WARNING: SpecGenerator failed: {exc}")
            return self._write_fallback_spec()

    def _write_fallback_spec(self) -> Path:
        spec_path = self.specs_dir / f"{self.report_id}.spec"
        spec_path.write_text(
            f"# Fallback spec - {self.report_id}\n\n"
            "## Open Site\n\n"
            "* Open browser and navigate to base URL\n"
            "* Take a screenshot\n",
            encoding="utf-8",
        )
        return spec_path

    def _write_env(self, url: str):
        env_dir = EXECUTION_DIR / "env" / "default"
        env_dir.mkdir(parents=True, exist_ok=True)
        (env_dir / "default.properties").write_text(
            f"# Auto-generated by gauge_runner.py\n"
            f"gauge_screenshots_dir = {self.screenshots_dir}\n"
            f"gauge_reports_dir = {self.reports_dir}\n"
            f"BASE_URL = {url}\n",
            encoding="utf-8",
        )

    def _execute_gauge(self, spec_path: Path) -> tuple[str, int]:
        timeout = int(os.getenv("GAUGE_TIMEOUT", 60))
        try:
            result = subprocess.run(
                ["gauge", "run", "--verbose", str(spec_path)],
                cwd=str(EXECUTION_DIR),
                capture_output=True, text=True, timeout=timeout,
            )
            return (result.stdout + "\n" + result.stderr).strip(), result.returncode
        except FileNotFoundError:
            return (
                "gauge binary not found.\n"
                "Install: https://gauge.org/get-started/\n"
                "Then: gauge install python && gauge install html-report"
            ), 1
        except subprocess.TimeoutExpired:
            return f"Gauge timed out after {timeout}s.", 1
        except Exception as exc:
            return str(exc), 1

    def _parse_results(self, raw_output: str, exit_code: int) -> dict:
        passed, failed = 0, 0
        summary = re.search(r"(\d+)\s+scenarios?,\s*(\d+)\s+failed", raw_output)
        if summary:
            total  = int(summary.group(1))
            failed = int(summary.group(2))
            passed = total - failed
        else:
            passed = len(re.findall(r"\bPASS\b", raw_output))
            failed = len(re.findall(r"\bFAIL\b", raw_output))
        dur = re.search(r"(\d+m\s*\d+\.\d+s|\d+\.\d+s)", raw_output)
        return {
            "exit_code":  exit_code,
            "passed":     passed,
            "failed":     failed,
            "success":    exit_code == 0,
            "duration":   dur.group(1) if dur else "unknown",
            "raw_output": raw_output[:6000],
        }