"""
fix_and_run.py
==============
One-shot fix script that:
  1. Finds the most recent JSON report
  2. Regenerates the .spec with ONLY steps that exist in ai_steps.py
  3. Regenerates ai_steps.py
  4. Fixes default.properties (forward-slash paths + GAUGE_PYTHON_COMMAND)
  5. Runs gauge
  6. Writes/updates the _results.json so the web report shows charts

Run from project root:
    python fix_and_run.py

Or target a specific report:
    python fix_and_run.py --report_id 20260304_105135_9d5ca00e
"""

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT          = Path(__file__).parent
EXECUTION_DIR = ROOT / "execution_layer"
SPECS_DIR     = EXECUTION_DIR / "specs"
STEP_IMPL_DIR = EXECUTION_DIR / "step_impl"
JSON_STORE    = ROOT / "intelligence_layer" / "json_store"
REPORTS_DIR   = ROOT / "reports"
SCREENSHOTS   = REPORTS_DIR / "screenshots"

sys.path.insert(0, str(ROOT))


def section(title):
    print(f"\n{'='*60}")
    print(f"  {title}")
    print(f"{'='*60}")


# ─────────────────────────────────────────────────────────────────────────────
# Step 1 — Find JSON
# ─────────────────────────────────────────────────────────────────────────────

def find_json(report_id=None) -> Path:
    if report_id:
        p = JSON_STORE / f"{report_id}.json"
        if not p.exists():
            print(f"[ERROR] {p} not found")
            sys.exit(1)
        return p
    files = sorted(JSON_STORE.glob("*.json"),
                   key=lambda f: f.stat().st_mtime, reverse=True)
    if not files:
        print("[ERROR] No JSON files found. Run main_pipeline.py first.")
        sys.exit(1)
    return files[0]


# ─────────────────────────────────────────────────────────────────────────────
# Step 2 — Regenerate spec
# ─────────────────────────────────────────────────────────────────────────────

def regenerate_spec(json_path: Path) -> Path:
    from spec_generator import SpecGenerator
    gen       = SpecGenerator(json_path=json_path, output_dir=SPECS_DIR)
    spec_path = gen.generate()

    # Verify no ValidationError-prone steps remain
    content = spec_path.read_text(encoding="utf-8")
    bad = []
    for line in content.splitlines():
        stripped = line.strip()
        if not stripped.startswith("*"):
            continue
        # Steps with angle brackets that are NOT proper Gauge params will fail
        if re.search(r"<(?!\w+>)", stripped):
            bad.append(stripped)

    if bad:
        print(f"  WARNING: {len(bad)} steps may cause ParseErrors:")
        for b in bad[:5]:
            print(f"    {b}")

    lines_with_steps = [l for l in content.splitlines() if l.strip().startswith("*")]
    print(f"  Spec has {len(lines_with_steps)} step lines")
    return spec_path


# ─────────────────────────────────────────────────────────────────────────────
# Step 3 — Regenerate ai_steps.py
# ─────────────────────────────────────────────────────────────────────────────

def regenerate_steps(json_path: Path):
    from step_impl_generator import StepImplGenerator
    output = STEP_IMPL_DIR / "ai_steps.py"
    STEP_IMPL_DIR.mkdir(exist_ok=True)
    StepImplGenerator(json_path=json_path, output_path=output).generate()
    lines = len(output.read_text(encoding="utf-8").splitlines())
    print(f"  ai_steps.py: {lines} lines")

    # Print registered steps
    content = output.read_text(encoding="utf-8")
    steps   = re.findall(r'@step\("(.+?)"\)', content)
    print(f"  Registered @steps: {len(steps)}")
    for s in steps:
        print(f"    • {s}")


# ─────────────────────────────────────────────────────────────────────────────
# Step 4 — Fix default.properties
# ─────────────────────────────────────────────────────────────────────────────

def fix_properties(url: str):
    env_dir = EXECUTION_DIR / "env" / "default"
    env_dir.mkdir(parents=True, exist_ok=True)

    # Use forward slashes — backslashes break Gauge on Windows
    screenshots_fwd = SCREENSHOTS.as_posix()
    reports_fwd     = REPORTS_DIR.as_posix()

    props = "\n".join([
        "# Auto-generated by fix_and_run.py",
        f"GAUGE_PYTHON_COMMAND = {sys.executable}",
        f"gauge_screenshots_dir = {screenshots_fwd}",
        f"gauge_reports_dir = {reports_fwd}",
        f"BASE_URL = {url}",
        "",
    ])
    (env_dir / "default.properties").write_text(props, encoding="utf-8")
    print(f"  Written: {env_dir / 'default.properties'}")
    print(f"  GAUGE_PYTHON_COMMAND = {sys.executable}")
    print(f"  gauge_screenshots_dir = {screenshots_fwd}")


# ─────────────────────────────────────────────────────────────────────────────
# Step 5 — Run gauge
# ─────────────────────────────────────────────────────────────────────────────

def run_gauge(spec_path: Path) -> tuple[str, int]:
    print(f"  Running: gauge run --verbose {spec_path.name}")
    print(f"  cwd:     {EXECUTION_DIR}")

    try:
        result = subprocess.run(
            ["gauge", "run", "--verbose", str(spec_path)],
            cwd=str(EXECUTION_DIR),
            capture_output=True,
            text=True,
            timeout=180,
        )
        combined = (result.stdout + "\n" + result.stderr).strip()
        print(f"  Exit code: {result.returncode}")

        # Print last 1500 chars of output
        print("\n  ── Gauge Output (last 1500 chars) ──")
        print(combined[-1500:])
        return combined, result.returncode

    except FileNotFoundError:
        msg = "gauge binary not found"
        print(f"  ERROR: {msg}")
        return msg, 1
    except subprocess.TimeoutExpired:
        msg = "Gauge timed out after 180s"
        print(f"  ERROR: {msg}")
        return msg, 1
    except Exception as exc:
        print(f"  ERROR: {exc}")
        return str(exc), 1


# ─────────────────────────────────────────────────────────────────────────────
# Step 6 — Parse results & write _results.json
# ─────────────────────────────────────────────────────────────────────────────

def parse_and_save(raw: str, exit_code: int, report_id: str) -> dict:
    passed = failed = skipped = 0

    # Try "X scenarios, Y failed"
    m = re.search(r"Scenarios:\s+(\d+)\s+executed\s+(\d+)\s+passed\s+(\d+)\s+failed\s+(\d+)\s+skipped", raw)
    if m:
        passed  = int(m.group(2))
        failed  = int(m.group(3))
        skipped = int(m.group(4))
    else:
        m2 = re.search(r"(\d+)\s+scenarios?,\s*(\d+)\s+failed", raw)
        if m2:
            total  = int(m2.group(1))
            failed = int(m2.group(2))
            passed = total - failed
        else:
            passed = len(re.findall(r"\bPassed\b", raw))
            failed = len(re.findall(r"\bFailed\b", raw))

    dur = re.search(r"Total time taken:\s*(.+)", raw)
    if not dur:
        dur = re.search(r"(\d+m\s*\d+\.\d+s|\d+\.\d+s)", raw)

    results = {
        "exit_code":  exit_code,
        "passed":     passed,
        "failed":     failed,
        "skipped":    skipped,
        "success":    exit_code == 0,
        "duration":   dur.group(1).strip() if dur else "unknown",
        "raw_output": raw[:8000],
    }

    REPORTS_DIR.mkdir(exist_ok=True)
    out_path = REPORTS_DIR / f"{report_id}_results.json"
    out_path.write_text(json.dumps(results, indent=2))
    print(f"\n  Results saved -> {out_path}")
    print(f"  Passed: {passed}  Failed: {failed}  Skipped: {skipped}")
    return results


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Fix and re-run gauge tests")
    parser.add_argument("--report_id", default="", help="Specific report ID to use")
    args = parser.parse_args()

    # ── 1. Find JSON ──────────────────────────────────────────────────────────
    section("Step 1: Find JSON report")
    json_path = find_json(args.report_id or None)
    data      = json.loads(json_path.read_text(encoding="utf-8"))
    report_id = data.get("report_id", json_path.stem)
    url       = data.get("url", "https://example.com")
    print(f"  Report ID : {report_id}")
    print(f"  URL       : {url}")
    print(f"  Test cases: {len(data.get('test_cases', []))}")

    # ── 2. Regenerate spec ────────────────────────────────────────────────────
    section("Step 2: Regenerate .spec file")
    spec_path = regenerate_spec(json_path)
    print(f"  Spec: {spec_path}")

    # ── 3. Regenerate ai_steps.py ─────────────────────────────────────────────
    section("Step 3: Regenerate ai_steps.py")
    regenerate_steps(json_path)

    # ── 4. Fix properties ─────────────────────────────────────────────────────
    section("Step 4: Fix default.properties")
    SCREENSHOTS.mkdir(parents=True, exist_ok=True)
    fix_properties(url)

    # ── 5. Run gauge ──────────────────────────────────────────────────────────
    section("Step 5: Run Gauge")
    raw, code = run_gauge(spec_path)

    # ── 6. Save results ───────────────────────────────────────────────────────
    section("Step 6: Save results")
    results = parse_and_save(raw, code, report_id)

    # ── Summary ───────────────────────────────────────────────────────────────
    section("DONE")
    print(f"""
  Report ID  : {report_id}
  Passed     : {results['passed']}
  Failed     : {results['failed']}
  Skipped    : {results['skipped']}
  Duration   : {results['duration']}
  Web report : http://localhost:5000/report/{report_id}

  If passed/failed are still 0, Gauge has ValidationErrors.
  Check the output above for lines like:
    [ValidationError] Step implementation not found => '...'
  Those steps need to be added to ai_steps.py or the spec must be fixed.
    """)


if __name__ == "__main__":
    main()